version: '3'

services:
  postgres:
    image: postgres:latest
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
volumes:
  postgres:
    driver: local
